/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


/**
 *
 * @author cata
 */
public class VRecuperarContraseña extends javax.swing.JFrame {

    /**
     * @return the cbxPregunta
     */
    public static javax.swing.JComboBox getCbxPregunta() {
        return cbxPregunta;
    }

    /**
     * @param aCbxPregunta the cbxPregunta to set
     */
    public static void setCbxPregunta(javax.swing.JComboBox aCbxPregunta) {
        cbxPregunta = aCbxPregunta;
    }

    /**
     * @return the LblCoctraseña
     */
    public static javax.swing.JLabel getLblCoctraseña() {
        return LblCoctraseña;
    }

    /**
     * @param aLblCoctraseña the LblCoctraseña to set
     */
    public static void setLblCoctraseña(javax.swing.JLabel aLblCoctraseña) {
        LblCoctraseña = aLblCoctraseña;
    }

    /**
     * Creates new form VOlvidoContraseña
     */
    public VRecuperarContraseña() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblPregunta = new javax.swing.JPanel();
        TxtRespuesta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BtnAceptar = new javax.swing.JButton();
        LblRespuesta = new javax.swing.JLabel();
        BtnCambiarContraseña = new javax.swing.JButton();
        LblUsuario = new javax.swing.JLabel();
        TxtUsuario = new javax.swing.JTextField();
        LblContraseña = new javax.swing.JLabel();
        BtnBuscar = new javax.swing.JButton();
        cbxPregunta = new javax.swing.JComboBox();
        LblCoctraseña = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Responda la pregunta que eligio al registrarse");

        BtnAceptar.setText("Aceptar");
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });

        LblRespuesta.setText("Respuesta");

        BtnCambiarContraseña.setText("Cambiar contraseña");
        BtnCambiarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCambiarContraseñaActionPerformed(evt);
            }
        });

        LblUsuario.setText("Nombre usuario");

        TxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsuarioActionPerformed(evt);
            }
        });

        LblContraseña.setText("Su contraseña es:");

        BtnBuscar.setText("...");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        cbxPregunta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Primer nombre de su mamá", "Nombre de su primer mascota", "Animal favorito", "Nombre de su padrino de bautizo", "Comida favotita" }));
        cbxPregunta.setEnabled(false);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IMAGEN CDI.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Ravie", 0, 24)); // NOI18N
        jLabel4.setText("RECUPERAR");

        jLabel5.setFont(new java.awt.Font("Ravie", 0, 24)); // NOI18N
        jLabel5.setText("CONTRASEÑA");

        javax.swing.GroupLayout LblPreguntaLayout = new javax.swing.GroupLayout(LblPregunta);
        LblPregunta.setLayout(LblPreguntaLayout);
        LblPreguntaLayout.setHorizontalGroup(
            LblPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LblPreguntaLayout.createSequentialGroup()
                .addGroup(LblPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LblPreguntaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(LblPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LblPreguntaLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(BtnCambiarContraseña))
                            .addComponent(LblCoctraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(LblPreguntaLayout.createSequentialGroup()
                        .addGroup(LblPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LblPreguntaLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(LblPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)))
                            .addGroup(LblPreguntaLayout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addGroup(LblPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblUsuario)
                                    .addComponent(TxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addGroup(LblPreguntaLayout.createSequentialGroup()
                                        .addComponent(cbxPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(LblRespuesta)
                                    .addComponent(TxtRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(LblPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(BtnAceptar)
                                        .addComponent(LblContraseña)))))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        LblPreguntaLayout.setVerticalGroup(
            LblPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LblPreguntaLayout.createSequentialGroup()
                .addGroup(LblPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LblPreguntaLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LblPreguntaLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addGroup(LblPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LblPreguntaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LblUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(67, 67, 67))
                    .addGroup(LblPreguntaLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(LblPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnBuscar)
                            .addComponent(cbxPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(13, 13, 13)
                .addComponent(LblRespuesta)
                .addGap(18, 18, 18)
                .addComponent(TxtRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(LblPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LblPreguntaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(LblCoctraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(LblPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnCambiarContraseña)
                            .addComponent(BtnAceptar))
                        .addGap(52, 52, 52))
                    .addGroup(LblPreguntaLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(LblContraseña)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
     datos.DContraserña.recuperarContaseña(TxtUsuario.getText(), logica.LEncriptar.Encriptar(TxtRespuesta.getText()));
    }//GEN-LAST:event_BtnAceptarActionPerformed

    private void TxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsuarioActionPerformed

    private void BtnCambiarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCambiarContraseñaActionPerformed
       ManejadorDePantalla.AbrirPantallaCambiarContraseña();
       ManejadorDePantalla.CerrrarPantallaRecuperarContraseña();
    }//GEN-LAST:event_BtnCambiarContraseñaActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        datos.DContraserña.buscarPregunta( TxtUsuario.getText());
    }//GEN-LAST:event_BtnBuscarActionPerformed

    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VRecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VRecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VRecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VRecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VRecuperarContraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnCambiarContraseña;
    private static javax.swing.JLabel LblCoctraseña;
    private javax.swing.JLabel LblContraseña;
    private javax.swing.JPanel LblPregunta;
    private javax.swing.JLabel LblRespuesta;
    private javax.swing.JLabel LblUsuario;
    private javax.swing.JTextField TxtRespuesta;
    private javax.swing.JTextField TxtUsuario;
    private static javax.swing.JComboBox cbxPregunta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the LblContraseña
     */
    public javax.swing.JLabel getLblContraseña() {
        return LblContraseña;
    }

    /**
     * @param LblContraseña the LblContraseña to set
     */
    public void setLblContraseña(javax.swing.JLabel LblContraseña) {
        this.LblContraseña = LblContraseña;
    }

}
